# Generated by Django 5.0.3 on 2024-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='hostname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='railway_line',
            field=models.CharField(choices=[('Midland', 'Midland'), ('FAL', 'FAL'), ('Fremantle', 'Fremantle'), ('Joondalup', 'Joondalup'), ('Ellenbrook', 'Ellenbrook'), ('Thornlie', 'Thornlie'), ('City Precinct', 'City Precinct'), ('Mandurah', 'Mandurah')], max_length=100),
        ),
        migrations.AddField(
        model_name='results',
        name='timestamp',
        field=models.DateTimeField(auto_now_add=True),
        preserve_default=False,
    ),
    ]
